---
title: "HW6_Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
```



Column {.sidebar}
-----------------------------------------------------------------------
```{r load data}
instacart = 
  read_csv("../data/orders_train_allvars.csv") %>%
  clean_names() 

```

```{r  selectInput widget}
departments = instacart %>% distinct(departments) %>% pull()
selectInput("Department", label = h3("Select Department"),
            choices = departments, selected = "alcohol")
```

```{r widget2}
aisles = instacart %>% distinct(aisle) %>% pull()
selectInput("Aisle", label = h3("Select Aisle"),
            choices = aisles, selected = "bakery desserts")
```

```{r radioButtons widget3}
dow = instacart %>%
  mutate(order_dow = as.factor(order_dow)) %>%
  mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>%
  distinct(order_dow) %>% pull()

radioButtons("Day of Week", label = h3("Select Day of Week"),
            choices = dow, selected = "sunday")
```

Row
-----------------------------------------------------------------------

### Chart A

```{r A Bar graph of most popular product in each deparment}
instacart %>%
    group_by(department, product_name) %>%
    summarize(orders = n()) %>%
    group_by(department) %>%
    summarise(most_popular = product_name[which.max(orders)],
           orders = max(orders)) %>%
  #filter(department == input$Department,
           #aisle == input$Aisle) %>%
  plot_ly( x = ~most_popular, y = ~orders, color = ~department, type = "bar")
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r B Box plot of the hour of the day the order was placed on across department}
renderPlotly({ 
 instacart %>%
  group_by(aisle) %>%
  mutate(iqr_hr_of_day = IQR(order_hour_of_day)) %>% 
  ungroup(aisle) %>% 
  mutate(aisle = forcats::fct_reorder(aisle,iqr_hr_of_day)) %>%
  group_by(aisle) %>% 
  #filter(department == "produce") %>%
  filter(department == input$Department,
           aisle == input$Aisle) %>%
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box",
          colors = "Set2")

})
```

### Chart C

```{r C Bar graph number of orders placed during a week }
renderPlotly({ 
 instacart %>% 
  group_by(department, order_dow) %>%
  #filter(department == c("bakery", "deli", "frozen", "produce")) %>%
  summarise(orders = n()) %>%
  mutate(order_dow = as.factor(order_dow)) %>%
  mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>% 
  group_by(order_dow) %>%
  plot_ly(y = ~orders, x = ~order_dow, color = ~department, type = "bar",
          colors = "Set3")
})
```

