---
title: "p8105_hw6_xs2329_yz3306"
author: "Xiangyu Shi, Yulan Zhang"
date: "November 14, 2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill

---
Collaborators for this project:

Xiangyu Shi (UNI: xs2329 )
Yulan Zhang (UNI: yz3306)



```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
```




Row {data-width=350}
-----------------------------------------------------------------------
```{r}
instacart = 
  read_csv("../data/orders_train_allvars.csv") %>%
  clean_names() %>%
  filter(department == c("bakery", "deli", "frozen", "produce"))
```

### A. Bar graph of most popular product in each deparment

```{r}
instacart %>%
    group_by(department, order_dow) %>%
    mutate(orders = n()) %>%
    #group_by(department) %>%
    mutate(most_popular = product_name[which.max(orders)],
           orders = max(orders)) %>%
    ungroup() %>%
    mutate(most_popular = fct_reorder(most_popular, orders)) %>%
    mutate(order_dow = as.factor(order_dow)) %>%
    mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>%
  plot_ly( x = ~most_popular, y = ~orders, color = ~order_dow, type = "bar") 
```

Row {data-width=500}
-----------------------------------------------------------------------


### B Box plot of the hour of the day the order was placed on across department

```{r}
instacart %>%
  group_by(aisle) %>%
  mutate(iqr_hr_of_day = IQR(order_hour_of_day)) %>% 
  ungroup(aisle) %>% 
  mutate(aisle = forcats::fct_reorder(aisle,iqr_hr_of_day)) %>%
  group_by(aisle) %>% 
  #filter(department == c("produce", "frozen")) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box",
          colors = "Set2")

```



-----------------------------------------------------------------------

### C Bar graph number of orders placed during a week 

```{r}

  instacart %>% 
  group_by(department, order_dow) %>%
  #filter(department == c("bakery", "deli", "frozen", "produce")) %>%
  mutate(orders = n()) %>%
  ungroup() %>%
  mutate(order_dow = as.factor(order_dow)) %>%
  mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>% 
  group_by(order_dow) %>%
  plot_ly(y = ~orders, x = ~order_dow, color = ~department, type = "bar",
          colors = "Set3")

```




